default:
  only:
    variables:
      - $CI_SERVER_HOST == "gitlab.mnl.de"

stages:
  - build
  - test
  - deploy

test-pages:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/ruby:3.2
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - git fetch origin gh-pages
    - git checkout gh-pages
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
      
deploy-pages:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/ruby:3.2
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - git fetch origin gh-pages
    - git checkout gh-pages
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  environment: production
