stages:
  - build
  - test
  - deploy

.any-job:
  rules:
    - if: $CI_SERVER_HOST == "gitlab.mnl.de"

.gradle-job:
  extends: .any-job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/fedora:40
  before_script:
    - dnf install -y java-21-openjdk nodejs python gcc gcc-c++ git podman
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
build-gradle:
  stage: build
  extends: .gradle-job  
  script:
    - ./gradlew -Pdocker.registry=$CI_REGISTRY_IMAGE pushImage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
      - node_modules
      - "*/build"

.pages-job:
  extends: .any-job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/ruby:3.2
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - git fetch origin gh-pages
    - git checkout gh-pages
    - gem install bundler
    - bundle install

test-pages:
  stage: test
  extends: .pages-job
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
      
deploy-pages:
  stage: deploy
  extends: .pages-job
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  environment: production
