jdbldDirectory = _jdbld
# jdbldVersion = 0.1.1-SNAPSHOT

extensionsSnapshotRepository = https://central.sonatype.com/repository/maven-snapshots/
buildExtensions =  \
    org.jdrupes:jdbld-ext-git:0.8.0,\
    org.jdrupes:jdbld-ext-nodejs:0.5.0

javaHome = /usr/lib/jvm/temurin-25-jdk/
