jdbldDirectory = _jdbld
jdbldVersion = 0.0.29-SNAPSHOT

extensionsSnapshotRepository = https://central.sonatype.com/repository/maven-snapshots/
# buildExtensions = org.eclipse.jgit:org.eclipse.jgit:7.3.0.202506031305-r
buildExtensions =  \
    org.jdrupes.gitversioning:core:0.1.0,\
    org.jdrupes:jdbld-ext-nodejs:0.0.29-SNAPSHOT

javaHome = /usr/lib/jvm/java-25
