# See [rules](https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml)

# Default state for all rules
default: true

# MD007/ul-indent : Unordered list indentation : 
# https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md007.md
MD007:
  # Spaces for indent
  indent: 2
  # Whether to indent the first level of the list
  start_indented: true
  # Spaces for first level indent (when start_indented is set)
  start_indent: 2

# MD025/single-title/single-h1 : Multiple top-level headings in the same document :
# https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md025.md
MD025:
  # Heading level
  level: 1
  # RegExp for matching title in front matter (disable)
  front_matter_title: ""

# MD036/no-emphasis-as-heading : Emphasis used instead of a heading : 
# https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md036.md
MD036: false
  
# MD043/required-headings : Required heading structure : 
# https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md043.md
MD043: false
