# The values in comments are the defaults.

"/Manager":
  "/Controller":
    # Values used when creating the PVC for the runner's data
    runnerData:
      storageClassName: null

    # Amount by which the current cpu count is devided when generating
    # the resource properties.  
    cpuOvercommit: 2

    # Amount by which the current ram size is devided when generating
    # the resource properties.
    ramOvercommit: 1.5

    # If defined, causes a load balancer service to be created.
    # May be a boolean or a string with nested yaml that
    # defines additional labels or annotations to be merged
    # into the service. 
    # loadBalancerService: |
    #   labels: {}
    #   annotations: {}

    # Explicitly specify the namespace to be managed (only for development).
    # namespace: vmop-dev
