apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  namespace: vmop-dev
  name: unittest-vm
spec:
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    
  loadBalancerService:
    labels:
      test2: null
      test3: added

  vm:
    # state: Running
    maximumRam: 4Gi
    currentRam: 2Gi
    maximumCpus: 4
    currentCpus: 2
    powerdownTimeout: 1
  
    networks:
    - user: {}
    disks:
    - cdrom:
        # image: ""
        image: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso
        # image: "Fedora-Workstation-Live-x86_64-38-1.6.iso"

    display:
      spice:
        port: 5812
