# The values in comments are the defaults.

"/Manager":
  "/Controller":
    namespace: vmop-dev
    runnerData:
      storageClassName: null
    loadBalancerService: |
      labels:
        test1: info
        test2: toBeDeleted
