# The values in comments are the defaults.

"/Manager":
  "/Controller":
    namespace: vmop-dev
    runnerData:
      storageClassName: null
    additionalServiceMetadata:
      labels:
        test1: remains
        test2: deleted
