# Used for running manager outside Kubernetes.
# Keep in sync with kustomize.yaml 
"/Manager":
  # If provided, is shown at top left before namespace
  # clusterName: "test"
  # The controller manages the VM
  "/Controller":
    namespace: vmop-dev
    "/Reconciler":
      runnerDataPvc:
        storageClassName: rook-cephfs
      loadBalancerService:
        labels:
          label1: label1
          label2: toBeReplaced
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.168.1
          metallb.universe.tf/ip-allocated-from-pool: single-common
          metallb.universe.tf/allow-shared-ip: single-common
      loggingProperties: |
        # Defaults for namespace (VM domain)
        handlers=java.util.logging.ConsoleHandler
        
        #org.jgrapes.level=FINE
        #org.jgrapes.core.handlerTracking.level=FINER
        
        org.jdrupes.vmoperator.runner.qemu.level=FINEST
        
        java.util.logging.ConsoleHandler.level=ALL
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.SimpleFormatter.format=%1$tb %1$td %1$tT %4$s %5$s%6$s%n
  "/GuiSocketServer":
    port: 8888
  "/GuiHttpServer":
    # This configures the GUI
    "/ConsoleWeblet":
      "/WebConsole":
        "/LoginConlet":
          users:
          - name: admin
            fullName: Administrator
            password: "$2b$05$NiBd74ZGdplLC63ePZf1f.UtjMKkbQ23cQoO2OKOFalDBHWAOy21."
          - name: test1
            fullName: Test Account 1
            password: "$2b$05$hZaI/jToXf/d3BctZdT38Or7H7h6Pn2W3WiB49p5AyhDHFkkYCvo2"
          - name: test2
            fullName: Test Account 2
            password: "$2b$05$hZaI/jToXf/d3BctZdT38Or7H7h6Pn2W3WiB49p5AyhDHFkkYCvo2"
          - name: test3
            fullName: Test Account 3
            password: "$2b$05$hZaI/jToXf/d3BctZdT38Or7H7h6Pn2W3WiB49p5AyhDHFkkYCvo2"
        "/RoleConfigurator":
          rolesByUser:
            # User admin has role admin
            admin:
            - admin
            test1:
            - user
            test2:
            - user
            test3:
            - user
            # All users have role other
            "*":
            - other
          replace: false
        "/RoleConletFilter":
          conletTypesByRole:
            # Admins can use all conlets
            admin:
            - "*"
            user:
            - org.jdrupes.vmoperator.vmaccess.VmAccess
            # Others cannot use any conlet (except login conlet to log out)
            other:
            - org.jgrapes.webconlet.oidclogin.LoginConlet
        "/ComponentCollector":
          "/VmAccess":
            displayResource:
              preferredIpVersion: ipv4
            syncPreviewsFor:
            - role: user
