# Used for running manager outside Kubernetes.
# Keep in sync with kustomize.yaml 
"/Manager":
  "/Controller":
    namespace: vmop-dev
    "/Reconciler":
      runnerData:
        storageClassName: null
