apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  namespace: vmop-dev
  name: test-vm
spec:
  image:
    repository: docker-registry.lan.mnl.de
    path: vmoperator/org.jdrupes.vmoperator.runner.qemu-arch
    pullPolicy: Always

  loadBalancerService:
    labels:
      test2: null
      test3: added

  vm:
    # state: Running
    bootMenu: yes
    maximumRam: "8 GiB"
    currentRam: "4 GiB"
    maximumCpus: 4
    currentCpus: 4
  
    networks:
    - tap:
        mac: "00:16:3e:33:58:10"
    disks:
    - volumeClaimTemplate:
        metadata:
          name: system
        spec:
          storageClassName: ""
          selector:
            matchLabels:
              app.kubernetes.io/name: vmrunner
              app.kubernetes.io/instance: test-vm
              vmrunner.jdrupes.org/disk: system
          resources:
            requests:
              storage: 40Gi
    - cdrom:
        image: ""
        # image: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso
        # image: "Fedora-Workstation-Live-x86_64-38-1.6.iso"

    display:
      spice:
        port: 5810
