kind: Secret
apiVersion: v1
metadata:
  name: test-vm-display-secret
  namespace: vmop-dev
  labels:
    app.kubernetes.io/name: vm-runner
    app.kubernetes.io/instance: test-vm
    app.kubernetes.io/component: display-secret
type: Opaque
data:
  display-password: dGVzdC12bQ==
  password-expiry: KzMw
