apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  namespace: vmop-dev
  name: test-vm
spec:
  image:
    source: registry.mnl.de/org/jdrupes/vm-operator/org.jdrupes.vmoperator.runner.qemu-arch:testing
    pullPolicy: Always

  permissions:
  - user: admin
    may: 
    - "*"

  resources:
    requests:
      cpu: 1
      memory: 2Gi

  guestShutdownStops: true
  
  cloudInit: {}
  
  vm:
    # state: Running
    bootMenu: yes
    useTpm: true
    maximumRam: 8Gi
    currentRam: 4Gi
    maximumCpus: 4
    currentCpus: 4
  
    networks:
    # No bridge on test cluster
    - user: {}

    disks:
    - volumeClaimTemplate:
        metadata:
          name: system
        spec:
          storageClassName: ""
          selector:
            matchLabels:
              app.kubernetes.io/name: vmrunner
              app.kubernetes.io/instance: test-vm
              vmrunner.jdrupes.org/disk: system
          resources:
            requests:
              storage: 40Gi
    - cdrom:
        image: ""
        # image: https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso
        # image: "Fedora-Workstation-Live-x86_64-38-1.6.iso"

    display:
      spice:
        port: 5810
        generateSecret: true

  loadBalancerService: {}
