apiVersion: "vmoperator.jdrupes.org/v1"
kind: VmPool
metadata:
  namespace: vmop-dev
  name: test-vms
spec:
  retention: "PT1m"
  permissions:
  - user: admin
    may:
    - accessConsole
  - role: user
    may:
    - accessConsole
