apiVersion: "vmoperator.jdrupes.org/v1"
kind: VmPool
metadata:
  namespace: vmop-dev
  name: test-vms
spec:
  permissions:
  - user: admin
    may:
    - accessConsole
  - user: test
    may:
    - accessConsole
