apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmopconfigs.vmoperator.jdrupes.org
spec:
  group: vmoperator.jdrupes.org
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              imageRepository:
                type: object
                description: Defines the image repository volume.
                properties: {}
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: vmopconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: vmopconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: VmOpConfig
    listKind: VmOpConfigList
