apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmpools.vmoperator.jdrupes.org
spec:
  group: vmoperator.jdrupes.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                permissions:
                  type: array
                  description: >-
                    Defines permissions for accessing and manipulating the Pool.
                  items:
                    type: object
                    description: >-
                      Permissions can be granted to a user or to a role.
                    oneOf:
                    - required:
                      - user
                    - required:
                      - role
                    properties:
                      user:
                        type: string
                      role:
                        type: string
                      may:
                        type: array
                        items:
                          type: string
                          enum:
                          - start
                          - stop
                          - reset
                          - accessConsole
                          - "*"
                        default: []
              required:
              - permissions
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: vmpools
    # singular name to be used as an alias on the CLI and for display
    singular: vmpool
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: VmPool
    listKind: VmPoolList
