apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  namespace: qemu-vms
  name: test-vm
spec:
  image:
    repository: docker-registry.lan.mnl.de
    path: vmoperator/org.jdrupes.vmoperator.runner.qemu-arch
    pullPolicy: Always

  vm:
    maximumCpus: 4
    currentCpus: 4
    maximumRam: "8 GiB"
    currentRam: "4 GiB"
  
    networks:
    - tap:
        mac: "00:16:3e:33:59:10"
    disks:
    - volumeClaimTemplate:
#        metadata:
#          name: test-vm-system
        spec:
          storageClassName: ""
          selector:
            matchLabels:
              app.kubernetes.io/name: vmrunner
              app.kubernetes.io/instance: test-vm
              vmrunner.jdrupes.org/disk: system
          resources:
            requests:
              storage: 40Gi

#    - hostDevice: /dev/vgmain/test-vm
    display:
      spice:
        port: 5910
