apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  namespace: qemu-vms
  name: test-vm
spec:

  image:
    # Defaults:
    # repository: ghcr.io
    # path: mnlipp/org.jdrupes.vmoperator.runner.qemu-arch
    # version: latest
    pullPolicy: Always

  vm:
    maximumCpus: 4
    currentCpus: 4
    maximumRam: "8 GiB"
    currentRam: "4 GiB"
  
    networks:
    - tap: {}
    
    disks:
    - volumeClaimTemplate:
        metadata:
          name: test-vm-system
        spec:
          storageClassName: ""
          selector:
            matchLabels:
              app.kubernetes.io/name: vmrunner
              app.kubernetes.io/instance: test-vm
              vmrunner.jdrupes.org/disk: system
          resources:
            requests:
              storage: 40Gi

#    - hostDevice: /dev/vgmain/test-vm
    display:
      spice:
        port: 5910
