apiVersion: "vmoperator.jdrupes.org/v1"
kind: VirtualMachine
metadata:
  name: test-vm
spec:
  image:
    repository: docker-registry.lan.mnl.de
    path: vmoperator/org.jdrupes.vmoperator.runner.qemu-arch
    pullPolicy: Always

  vm:
    maximumCpus: 4
    currentCpus: 4
    maximumRam: "8 GiB"
    currentRam: "4 GiB"
  
    networks:
    - tap:
        mac: "00:16:3e:33:59:10"
    disks:
    - hostDevice: /dev/vgmain/test-vm
    displays:
    - spice:
        port: 5910
