apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-operator
  labels:
    app.kubernetes.io/name: vm-operator
rules:
- apiGroups:
  - vmoperator.jdrupes.org
  resources:
  - vms
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - delete
  - patch
