apiVersion: v1
kind: Service
metadata:
  name: vm-operator
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: manager
