apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-runner
  labels:
    app.kubernetes.io/name: vm-operator
rules:
- apiGroups:
  - vmoperator.jdrupes.org
  resources:
  - vms
  verbs:
  - list
  - get
- apiGroups:
  - vmoperator.jdrupes.org
  resources:
  - vms/status
  verbs:
  - patch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
