apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-runner
  labels:
    app.kubernetes.io/name: vm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-runner
subjects:
- kind: ServiceAccount
  name: vm-runner
