apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/mnlipp/VM-Operator/deploy

namespace: vmop-demo

patches:
# Use storage class rook-cephfs for the shared image repository
- patch: |-
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: vmop-image-repository
    spec:
      storageClassName: rook-cephfs

# Use storage class rook-cepfs for the runner's data (e.g. EFI vars)
- patch: |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: vm-operator
    data:
      config.yaml: |
        "/Manager":
          "/Controller":
            "/Reconciler":
              runnerData:
                storageClassName: rook-cephfs
