kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ cr.namespace() }
  name: ${ disk.generatedPvcName }
  labels:
    app.kubernetes.io/name: ${ constants.APP_NAME }
    app.kubernetes.io/instance: ${ cr.name() }
    app.kubernetes.io/managed-by: ${ constants.VM_OP_NAME }
  <#if disk.volumeClaimTemplate.metadata??
    && disk.volumeClaimTemplate.metadata.annotations??>
  annotations:
    ${ toJson(disk.volumeClaimTemplate.metadata.annotations) }
  </#if>
spec:
  ${ toJson(disk.volumeClaimTemplate.spec) }
