apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${ cr.metadata.namespace.asString }
  name: ${ cr.metadata.name.asString }
  labels:
    app.kubernetes.io/name: ${ constants.APP_NAME }
    app.kubernetes.io/instance: ${ cr.metadata.name.asString }
    app.kubernetes.io/managed-by: ${ constants.VM_OP_NAME }
  annotations:
    vmoperator.jdrupes.org/version: ${ managerVersion }
  ownerReferences:
  - apiVersion: ${ cr.apiVersion.asString }
    kind: ${ constants.VM_OP_KIND_VM }
    name: ${ cr.metadata.name.asString }
    uid: ${ cr.metadata.uid.asString }
    controller: false
  
data:
  config.yaml: |
    "/Runner":
      # The directory used to store data files. Defaults to (depending on 
      # values available):
      #  * $XDG_DATA_HOME/vmrunner/${ cr.metadata.name.asString }
      #  * $HOME/.local/share/vmrunner/${ cr.metadata.name.asString }
      #  * ./${ cr.metadata.name.asString }
      dataDir: /var/local/vm-data
      
      # The directory used to store runtime files. Defaults to (depending on 
      # values available):
      #  * $XDG_RUNTIME_DIR/vmrunner/${ cr.metadata.name.asString }
      #  * /tmp/$USER/vmrunner/${ cr.metadata.name.asString }
      #  * /tmp/vmrunner/${ cr.metadata.name.asString }
      # runtimeDir: "$XDG_RUNTIME_DIR/vmrunner/${ cr.metadata.name.asString }"
      
      # The template to use. Resolved relative to /usr/share/vmrunner/templates.
      # template: "Standard-VM-latest.ftl.yaml"
      <#if cr.spec.runnerTemplate?? && cr.spec.runnerTemplate.source?? >
      template: ${ cr.spec.runnerTemplate.source.asString }
      </#if>
    
      # The template is copied to the data diretory when the VM starts for
      # the first time. Subsequent starts use the copy unless this option is set.
      <#if cr.spec.runnerTemplate?? && cr.spec.runnerTemplate.update?? >
      updateTemplate: ${ cr.spec.runnerTemplate.update.asBoolean?c }
      </#if>
    
      # Define the VM (required)
      vm:
        # The VM's name (required)
        name: ${ cr.metadata.name.asString }
        
        # The machine's uuid. If none is specified, a uuid is generated
        # and stored in the data directory. If the uuid is important
        # (e.g. because licenses depend on it) it is recommaned to specify
        # it here explicitly or to carefully backup the data directory.
        # uuid: "generated uuid"
        <#if cr.spec.vm.machineUuid??>
        uuid: "${ cr.spec.vm.machineUuid.asString }"
        </#if>

        # Whether to provide a software TPM (defaults to false)
        # useTpm: false
        useTpm: ${ cr.spec.vm.useTpm.asBoolean?c }
        
        # How to boot (see https://github.com/mnlipp/VM-Operator/blob/main/org.jdrupes.vmoperator.runner.qemu/resources/org/jdrupes/vmoperator/runner/qemu/defaults.yaml):
        #  * bios
        #  * uefi[-4m]
        #  * secure[-4m]
        firmware: ${ cr.spec.vm.firmware.asString }
        
        # Whether to show a boot menu.
        # bootMenu: false
        bootMenu: ${ cr.spec.vm.bootMenu.asBoolean?c }
    
        # When terminating, a graceful powerdown is attempted. If it
        # doesn't succeed within the given timeout (seconds) SIGTERM
        # is sent to Qemu.
        # powerdownTimeout: 900
        powerdownTimeout: ${ cr.spec.vm.powerdownTimeout.asLong?c }
        
        # CPU settings
        cpuModel: ${ cr.spec.vm.cpuModel.asString }
        # Setting maximumCpus to 1 omits the "-smp" options. The defaults (0)
        # cause the corresponding property to be omitted from the "-smp" option.
        # If currentCpus is greater than maximumCpus, the latter is adjusted.
        <#if cr.spec.vm.maximumCpus?? >
        maximumCpus: ${ parseQuantity(cr.spec.vm.maximumCpus.asString)?c }
        </#if>
        <#if cr.spec.vm.cpuTopology?? >
        sockets: ${ cr.spec.vm.cpuTopology.sockets.asInt?c }
        diesPerSocket: ${ cr.spec.vm.cpuTopology.diesPerSocket.asInt?c }
        coresPerDie: ${ cr.spec.vm.cpuTopology.coresPerDie.asInt?c }
        threadsPerCore: ${ cr.spec.vm.cpuTopology.threadsPerCore.asInt?c }
        </#if>
        <#if cr.spec.vm.currentCpus?? >
        currentCpus: ${ parseQuantity(cr.spec.vm.currentCpus.asString)?c }
        </#if>
        
        # RAM settings
        # Maximum defaults to 1G
        maximumRam: "${ formatMemory(parseQuantity(cr.spec.vm.maximumRam.asString)) }"
        <#if cr.spec.vm.currentRam?? >
        currentRam: "${ formatMemory(parseQuantity(cr.spec.vm.currentRam.asString)) }"
        </#if>
        
        # RTC settings.
        # rtcBase: utc
        # rtcClock: rt
        rtcBase: ${ cr.spec.vm.rtcBase.asString }
        rtcClock: ${ cr.spec.vm.rtcClock.asString }
        
        # Network settings
        # Supported types are "tap" and "user" (for debugging). Type "user"
        # supports only the property "net".
        # network:
        # - type: tap
        #   bridge: br0
        #   device: virtio-net
        #   mac: (undefined)
        network:
        <#assign nwCounter = 0/>
        <#list cr.spec.vm.networks.asList() as itf>
        <#if itf.tap??>
        - type: tap
          device: ${ itf.tap.device.asString }
          bridge: ${ itf.tap.bridge.asString }
          <#if itf.tap.mac??>
          mac: "${ itf.tap.mac.asString }"
          </#if>
        <#elseif itf.user??>
        - type: user
          device: ${ itf.user.device.asString }
          <#if itf.user.net??>
          net: "${ itf.user.net.asString }"
          </#if>
        </#if>
        <#assign nwCounter += 1/>
        </#list>

        # There are no default drives. The supported types are "ide-cd"
        # and "raw". All types support a "bootindex" property.
        # Type "raw" can have a property "file" (if backed by a file on
        # the host) or a property "device" (if backed by a device).    
        # drives:
        # - type: ide-cd
        #   bootindex: (undefined)
        #   file: (undefined)
        drives:
        <#assign drvCounter = 0/>
        <#list cr.spec.vm.disks.asList() as disk>
        <#if disk.volumeClaimTemplate?? 
          && disk.volumeClaimTemplate.metadata??
          && disk.volumeClaimTemplate.metadata.name??>
          <#assign diskName = disk.volumeClaimTemplate.metadata.name.asString + "-disk">
        <#else>
          <#assign diskName = "disk-" + drvCounter>
        </#if>
        <#if disk.volumeClaimTemplate??> 
        - type: raw
          resource: /dev/${ diskName }
          <#if disk.bootindex??>
          bootindex: ${ disk.bootindex.asInt?c }
          </#if>
          <#assign drvCounter = drvCounter + 1/>
        </#if>
        <#if disk.cdrom??> 
        - type: ide-cd
          file: "${ disk.cdrom.image.asString }"
          <#if disk.bootindex??>
          bootindex: ${ disk.bootindex.asInt?c }
          </#if>
        </#if>
        </#list>
        
        display:
          <#if cr.spec.vm.display.spice??>
          spice:
            port: ${ cr.spec.vm.display.spice.port.asInt?c }
            <#if cr.spec.vm.display.spice.ticket??>
            ticket: "${ cr.spec.vm.display.spice.ticket.asString }"
            </#if>
            <#if cr.spec.vm.display.spice.streamingVideo??>
            ticket: "${ cr.spec.vm.display.spice.streamingVideo.asString }"
            </#if>
            usbRedirects: ${ cr.spec.vm.display.spice.usbRedirects.asInt?c }
          </#if>

  logging.properties: |
    handlers=java.util.logging.ConsoleHandler
    
    #org.jgrapes.level=FINE
    #org.jgrapes.core.handlerTracking.level=FINER
    
    org.jdrupes.vmoperator.runner.qemu.level=FINE
    
    java.util.logging.ConsoleHandler.level=ALL
    java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
    java.util.logging.SimpleFormatter.format=%1$tb %1$td %1$tT %4$s %5$s%6$s%n
