kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ cr.namespace() }
  name: ${ runnerDataPvcName }
  labels:
    app.kubernetes.io/name: ${ constants.APP_NAME }
    app.kubernetes.io/instance: ${ cr.name() }
    app.kubernetes.io/managed-by: ${ constants.VM_OP_NAME }
spec:
  accessModes:
  - ReadWriteOnce
  <#if reconciler.runnerDataPvc?? && reconciler.runnerDataPvc.storageClassName??>
  storageClassName: ${ reconciler.runnerDataPvc.storageClassName }
  </#if>
  resources:
    requests:
      storage: 1Mi
