kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ cr.metadata.namespace.asString }
  name: ${ disk.generatedPvcName }
  labels:
    app.kubernetes.io/name: ${ constants.APP_NAME }
    app.kubernetes.io/instance: ${ cr.metadata.name.asString }
    app.kubernetes.io/managed-by: ${ constants.VM_OP_NAME }
  <#if disk.volumeClaimTemplate.metadata??
    && disk.volumeClaimTemplate.metadata.annotations??>
  annotations:
    ${ disk.volumeClaimTemplate.metadata.annotations.toString() }
  </#if>
spec:
  ${ disk.volumeClaimTemplate.spec.toString() }
