kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ cr.metadata.namespace.asString }
  name: ${ cr.metadata.name.asString + "-data" }
  labels:
    app.kubernetes.io/name: ${ constants.APP_NAME }
    app.kubernetes.io/instance: ${ cr.metadata.name.asString }
    app.kubernetes.io/managed-by: ${ constants.VM_OP_NAME }
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
