# Global logging level
.level = INFO

# org.jdrupes.builder.level=CONFIG
# org.jdrupes.builder.level=FINE

# Specify handlers
handlers = java.util.logging.FileHandler 

# Configure the console handler
java.util.logging.ConsoleHandler.level=SEVERE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tT.%1$tL %4$s %5$s%6$s%n

# Configure the FileHandler
java.util.logging.FileHandler.pattern = jdbld.log
java.util.logging.FileHandler.append = false        # New file
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
