plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://jdrupes.org"
    
author: Michael N. Lipp

logo: VM-Operator.svg

tagline: VM-Operator by mnlipp 

description: >-
  A Kubernetes operator for running virtual machines (notably Qemu VMs)
  as pods.
