# Default values for vmrunner helm test.

image:
  repository: ghcr.io
  path: mnlipp/org.jdrupes.vmoperator.runner.qemu-arch
  version: latest
  pullPolicy: IfNotPresent

vm:
  # machineUuid: "generated"
  # host: "No default"
  useTpm: false
  firmware: "uefi"
  cpuModel: "host"
  maximumCpus: 4
  currentCpus: 2
  maximumMemory: "1G"
  # currentMemory: "Optional"
  rtcBase: "utc"
  spicePort: 5901
  disks:
  - device: /dev/vg/lv
    size: 40Gi
  networks:
  - bridge: {}
      # name: br0
      # mac: "Optional"
  powerdownTimeout: 60