name: Java CI with Jdbld

on:
  push: {}
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: doc_generation
  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # jdk 25 and xmlstarlet for jdbld, and graphviz for javadoc, 
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install openjdk-25-jdk xmlstarlet graphviz
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with jdbld
      run: >
        JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64/
        ./jdbld build javadoc
